language: scala

scala:
  - 2.12.4

services:
  - mysql

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_install:
  - mysql -e 'CREATE DATABASE example DEFAULT CHARACTER SET utf8;'

before_script:
  - mysql -uroot -Dexample < create_tables.sql
  - cp conf/application.test.conf conf/application.conf

script:
  - sbt coverage test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

