language: scala

scala:
  - 2.12.6

services:
  - mysql

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_install:
  - mysql -e 'create database example default character set utf8 collate utf8_general_ci;'

before_script:
  - cat /dev/null | sbt clean test:compile
  - cp conf/application.test.conf conf/application.conf
  - cp conf/db/conf/flyway.test.conf conf/db/conf/flyway.conf

script:
  - bash scripts/db-migrate.sh "CI"
  - sbt coverage test coverageReport
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

